# SPDX-FileCopyrightText: 2022 Dennis Gläser <dennis.glaeser@iws.uni-stuttgart.de>
# SPDX-License-Identifier: GPL-3.0-or-later

name: install-dependencies
inputs:
  compiler:
    required: true
runs:
  using: composite
  steps:
    - name: install-dependencies
      run: |
        # install latest clang from script
        COMPILER=${{ inputs.compiler }}
        if [[ "${COMPILER}" =~ .*"clang".* ]]; then
            VERSION="${COMPILER##*-}"
            echo "Installing clang version ${VERSION} from online script"
            sudo apt install wget software-properties-common
            wget https://apt.llvm.org/llvm.sh
            sudo /bin/bash llvm.sh ${VERSION}
        fi
        sudo apt install ${COMPILER} \
                         mpi-default-bin mpi-default-dev \
                         libhdf5-mpi-dev \
                         doxygen
        python3 -m pip install vtk
      shell: bash
