var gridformat_8hpp =
[
    [ "GridFormat::FileFormat::FormatWithOptions&lt; Format, Opts &gt;", "structGridFormat_1_1FileFormat_1_1FormatWithOptions.html", "structGridFormat_1_1FileFormat_1_1FormatWithOptions" ],
    [ "GridFormat::FileFormat::VTKXMLFormatBase&lt; VTKFormat &gt;", "structGridFormat_1_1FileFormat_1_1VTKXMLFormatBase.html", "structGridFormat_1_1FileFormat_1_1VTKXMLFormatBase" ],
    [ "GridFormat::Traits::WritesConnectivity&lt; APIDetail::SequentialOrParallelReader&lt; S, P &gt; &gt;", "structGridFormat_1_1Traits_1_1WritesConnectivity_3_01APIDetail_1_1SequentialOrParallelReader_3_01S_00_01P_01_4_01_4.html", null ],
    [ "GridFormat::WriterFactory&lt; FileFormat::VTI &gt;", "structGridFormat_1_1WriterFactory_3_01FileFormat_1_1VTI_01_4.html", null ],
    [ "GridFormat::ReaderFactory&lt; FileFormat::VTI &gt;", "structGridFormat_1_1ReaderFactory_3_01FileFormat_1_1VTI_01_4.html", null ],
    [ "GridFormat::WriterFactory&lt; FileFormat::VTR &gt;", "structGridFormat_1_1WriterFactory_3_01FileFormat_1_1VTR_01_4.html", null ],
    [ "GridFormat::ReaderFactory&lt; FileFormat::VTR &gt;", "structGridFormat_1_1ReaderFactory_3_01FileFormat_1_1VTR_01_4.html", null ],
    [ "GridFormat::WriterFactory&lt; FileFormat::VTS &gt;", "structGridFormat_1_1WriterFactory_3_01FileFormat_1_1VTS_01_4.html", null ],
    [ "GridFormat::ReaderFactory&lt; FileFormat::VTS &gt;", "structGridFormat_1_1ReaderFactory_3_01FileFormat_1_1VTS_01_4.html", null ],
    [ "GridFormat::WriterFactory&lt; FileFormat::VTP &gt;", "structGridFormat_1_1WriterFactory_3_01FileFormat_1_1VTP_01_4.html", null ],
    [ "GridFormat::ReaderFactory&lt; FileFormat::VTP &gt;", "structGridFormat_1_1ReaderFactory_3_01FileFormat_1_1VTP_01_4.html", null ],
    [ "GridFormat::WriterFactory&lt; FileFormat::VTU &gt;", "structGridFormat_1_1WriterFactory_3_01FileFormat_1_1VTU_01_4.html", null ],
    [ "GridFormat::ReaderFactory&lt; FileFormat::VTU &gt;", "structGridFormat_1_1ReaderFactory_3_01FileFormat_1_1VTU_01_4.html", null ],
    [ "GridFormat::WriterFactory&lt; FileFormat::VTKXMLTimeSeries&lt; F &gt; &gt;", "structGridFormat_1_1WriterFactory_3_01FileFormat_1_1VTKXMLTimeSeries_3_01F_01_4_01_4.html", null ],
    [ "GridFormat::WriterFactory&lt; FileFormat::VTKHDFImage &gt;", "structGridFormat_1_1WriterFactory_3_01FileFormat_1_1VTKHDFImage_01_4.html", null ],
    [ "GridFormat::ReaderFactory&lt; FileFormat::VTKHDFImage &gt;", "structGridFormat_1_1ReaderFactory_3_01FileFormat_1_1VTKHDFImage_01_4.html", null ],
    [ "GridFormat::WriterFactory&lt; FileFormat::VTKHDFImageTransient &gt;", "structGridFormat_1_1WriterFactory_3_01FileFormat_1_1VTKHDFImageTransient_01_4.html", null ],
    [ "GridFormat::ReaderFactory&lt; FileFormat::VTKHDFImageTransient &gt;", "structGridFormat_1_1ReaderFactory_3_01FileFormat_1_1VTKHDFImageTransient_01_4.html", null ],
    [ "GridFormat::WriterFactory&lt; FileFormat::VTKHDFUnstructured &gt;", "structGridFormat_1_1WriterFactory_3_01FileFormat_1_1VTKHDFUnstructured_01_4.html", null ],
    [ "GridFormat::ReaderFactory&lt; FileFormat::VTKHDFUnstructured &gt;", "structGridFormat_1_1ReaderFactory_3_01FileFormat_1_1VTKHDFUnstructured_01_4.html", null ],
    [ "GridFormat::WriterFactory&lt; FileFormat::VTKHDFUnstructuredTransient &gt;", "structGridFormat_1_1WriterFactory_3_01FileFormat_1_1VTKHDFUnstructuredTransient_01_4.html", null ],
    [ "GridFormat::ReaderFactory&lt; FileFormat::VTKHDFUnstructuredTransient &gt;", "structGridFormat_1_1ReaderFactory_3_01FileFormat_1_1VTKHDFUnstructuredTransient_01_4.html", null ],
    [ "GridFormat::WriterFactory&lt; FileFormat::VTKHDF &gt;", "structGridFormat_1_1WriterFactory_3_01FileFormat_1_1VTKHDF_01_4.html", null ],
    [ "GridFormat::ReaderFactory&lt; FileFormat::VTKHDF &gt;", "structGridFormat_1_1ReaderFactory_3_01FileFormat_1_1VTKHDF_01_4.html", null ],
    [ "GridFormat::WriterFactory&lt; FileFormat::VTKHDFTransient &gt;", "structGridFormat_1_1WriterFactory_3_01FileFormat_1_1VTKHDFTransient_01_4.html", null ],
    [ "GridFormat::ReaderFactory&lt; FileFormat::VTKHDFTransient &gt;", "structGridFormat_1_1ReaderFactory_3_01FileFormat_1_1VTKHDFTransient_01_4.html", null ],
    [ "GridFormat::WriterFactory&lt; FileFormat::PVD&lt; F &gt; &gt;", "structGridFormat_1_1WriterFactory_3_01FileFormat_1_1PVD_3_01F_01_4_01_4.html", null ],
    [ "GridFormat::ReaderFactory&lt; FileFormat::PVD&lt; PieceFormat &gt; &gt;", "structGridFormat_1_1ReaderFactory_3_01FileFormat_1_1PVD_3_01PieceFormat_01_4_01_4.html", null ],
    [ "GridFormat::ReaderFactory&lt; FileFormat::PVDClosure &gt;", "structGridFormat_1_1ReaderFactory_3_01FileFormat_1_1PVDClosure_01_4.html", null ],
    [ "GridFormat::WriterFactory&lt; FileFormat::Any &gt;", "structGridFormat_1_1WriterFactory_3_01FileFormat_1_1Any_01_4.html", null ],
    [ "GridFormat::WriterFactory&lt; FileFormat::AnyTimeSeries &gt;", "structGridFormat_1_1WriterFactory_3_01FileFormat_1_1AnyTimeSeries_01_4.html", null ],
    [ "GridFormat::ConversionOptions&lt; OutFormat, InFormat &gt;", "structGridFormat_1_1ConversionOptions.html", null ],
    [ "GridFormat::convert", "group__API.html#gaa262c55af3c1c39cf82bded8f77db38c", null ],
    [ "GridFormat::Formats::default_for", "group__API.html#ga19ce8850e7c649e701a6cab52a3ad5a5", null ],
    [ "GridFormat::Formats::default_for", "group__API.html#gaa73c41aeab2861bb23872f1498cb0eb4", null ],
    [ "GridFormat::null_communicator", "gridformat_8hpp.html#a86b425aee0f2f7c0a0deb3bd0ed5a7db", null ]
];