# SPDX-FileCopyrightText: 2022 Dennis Gläser <dennis.glaeser@iws.uni-stuttgart.de>
# SPDX-License-Identifier: MIT

name: test-installed-package
inputs:
  c_compiler:
    required: true
  cxx_compiler:
    required: true
runs:
  using: composite
  steps:
    - name: remove-build-directory
      run: rm -rf build
      shell: bash

    - name: install-gridformat
      run: |
        cmake -DCMAKE_C_COMPILER=${{inputs.c_compiler}} \
              -DCMAKE_CXX_COMPILER=${{inputs.cxx_compiler}} \
              -DGRIDFORMAT_BUILD_TESTS=OFF \
              -DGRIDFORMAT_BUILD_BINARIES=ON \
              -DCMAKE_INSTALL_PREFIX=$(pwd)/install \
              -DCMAKE_PREFIX_PATH=/gfmt-dependencies \
              -B build
        cmake --build build
        cmake --install build
      shell: bash

    - name: test-readme-cli-snippets
      run: |
        export PATH=$PATH:$(pwd)/install/bin
        python3 test/test_readme_cli_snippets.py \
          -c "-DCMAKE_C_COMPILER=${{inputs.c_compiler}} -DCMAKE_CXX_COMPILER=${{inputs.cxx_compiler}}"
      shell: bash

    - name: test-installed-pkg
      run: |
        mkdir installation-test && cp -r test installation-test
        pushd installation-test
          echo "cmake_minimum_required(VERSION 3.18)" > CMakeLists.txt
          echo "project(gridformat_test_suite VERSION 1.0.0)" >> CMakeLists.txt
          echo "enable_testing()" >> CMakeLists.txt
          echo "find_package(gridformat REQUIRED)" >> CMakeLists.txt
          echo "add_subdirectory(test)" >> CMakeLists.txt
          cmake -Dgridformat_ROOT=$(pwd)/../install \
                -DCMAKE_C_COMPILER=${{inputs.c_compiler}} \
                -DCMAKE_CXX_COMPILER=${{inputs.cxx_compiler}} \
                -DCMAKE_PREFIX_PATH=/gfmt-dependencies \
                -DCMAKE_BUILD_TYPE=Release \
                -B build
          if [[ ${{ github.ref_name }} != "main" ]]; then
            echo "Regression-testing sample files only for branch ${{ github.ref_name }}"
            export GRIDFORMAT_REGRESSION_SAMPLES_ONLY=true
          fi
          pushd build && make build_tests && ctest --output-on-failure && popd
      shell: bash

    - name: test-examples
      run: |
        pushd examples
          cmake -DCMAKE_C_COMPILER=${{inputs.c_compiler}} \
                -DCMAKE_CXX_COMPILER=${{inputs.cxx_compiler}} \
                -DCMAKE_PREFIX_PATH=/gfmt-dependencies \
                -Dgridformat_ROOT=$(pwd)/../install \
                -B build
        pushd build && make && ctest --output-on-failure
      shell: bash

    - name: test-examples-with-fetch-content
      run: |
        if [[ ${{ github.event_name }} == "pull_request" ]]; then
          GFMT_ORIGIN=${{ github.event.pull_request.head.repo.clone_url }}
          GFMT_TREE=${{ github.head_ref }}
        else
          GFMT_TREE=$GITHUB_HEAD_REF
          if [[ -z "$GFMT_TREE" ]]; then
            GFMT_TREE=$GITHUB_SHA
          fi
        fi
        rm -rf examples/build && pushd examples
          cmake -DCMAKE_C_COMPILER=${{inputs.c_compiler}} \
                -DCMAKE_CXX_COMPILER=${{inputs.cxx_compiler}} \
                -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_PREFIX_PATH=/gfmt-dependencies \
                -DGRIDFORMAT_FETCH_TREE="$GFMT_TREE" \
                -DGRIDFORMAT_ORIGIN="$GFMT_ORIGIN" \
                -B build
        pushd build && make && ctest --output-on-failure
      shell: bash
