# SPDX-FileCopyrightText: 2024 Dennis Gläser <dennis.a.glaeser@gmail.com>
# SPDX-License-Identifier: MIT

name: set-git-variables
runs:
  using: composite
  steps:
    - name: set-git-variables
      run: |
        if [[ ${{ github.event_name }} == "pull_request" ]]; then
          echo "GFMT_SOURCE_REMOTE=${{ github.event.pull_request.head.repo.clone_url }}" >> "$GITHUB_ENV"
          echo "GFMT_TARGET_REMOTE=${{ github.event.pull_request.base.repo.clone_url }}" >> "$GITHUB_ENV"
          echo "GFMT_SOURCE_TREE=${{ github.head_ref }}" >> "$GITHUB_ENV"
          echo "GFMT_TARGET_TREE=${{ github.base_ref }}" >> "$GITHUB_ENV"
        else
          echo "GFMT_SOURCE_REMOTE=${{ github.event.repository.clone_url }}" >> "$GITHUB_ENV"
          echo "GFMT_TARGET_REMOTE=${{ github.event.repository.clone_url }}" >> "$GITHUB_ENV"
          echo "GFMT_SOURCE_TREE=${{ github.head_ref }}" >> "$GITHUB_ENV"
          if [[ -z "${{github.head_ref}}" ]]; then
            echo "GFMT_SOURCE_TREE=${{ github.sha }}" >> "$GITHUB_ENV"
          fi
          echo "GFMT_TARGET_TREE=main" >> "$GITHUB_ENV"
        fi
      shell: bash
