# SPDX-FileCopyrightText: 2024 Dennis Gläser <dennis.a.glaeser@gmail.com>
# SPDX-License-Identifier: MIT

name: prepare-python-env
runs:
  using: composite
  steps:
    - name: prepare-python-env
      run: |
        source /gfmt-venv/bin/activate
        echo "PATH=$PATH" >> $GITHUB_ENV
      shell: bash
