# SPDX-FileCopyrightText: 2022 Dennis Gläser <dennis.glaeser@iws.uni-stuttgart.de>
# SPDX-License-Identifier: GPL-3.0-or-later

name: build-tests
inputs:
  c_compiler:
    required: true
  cxx_compiler:
    required: true
  build_dir:
    required: true
runs:
  using: composite
  steps:
    - name: remove-build-directory
      run: rm -rf ${{inputs.build_dir}}
      shell: bash

    - name: configure
      run: |
        cmake -DCMAKE_C_COMPILER=${{inputs.c_compiler}} \
              -DCMAKE_CXX_COMPILER=${{inputs.cxx_compiler}} \
              -DGRIDFORMAT_BUILD_TESTS=ON \
              -B ${{inputs.build_dir}}
      shell: bash

    - name: compile-tests
      run: pushd build && make build_tests && popd
      shell: bash
